### ISSUE TITLE
Unable to download files from URL that uses Non-ASCII characters

### ISSUE THREAD

**Issue by samperu** [lazaroblanc/Index-of-downloader#2]
Good morning 
I try to use your script but it didn´t downloaded any file from the https site, I want to download all files from this https site https://dl.304304.xyz/%E5%B0%9A%E6%9C%AA%E6%95%B4%E7%90%86/%E5%85%B1%E4%BA%AB2020.5.11/content/1_english/
it would help me to improve my english, maybe could you help me.

**Comment by lazaroblanc** [comment]
Thank you for your issue @samperu !
I took a look and was able to reproduce your error.
The issue is fixed with the latest commit.
Just download the [latest release ](https://github.com/lazaroblanc/Index-of-downloader/releases/latest) of the script ! :)

**Comment by rodionemo** [comment]
I trying to activate Index of downloader but it's not working can you help me?

**Comment by rodionemo** [comment]
I downloaded last update and is still not working

**Comment by lazaroblanc** [comment]
> I downloaded last update and is still not working

I haven't updated this repo in 4 years. Can you give me anything to go off as to *why* "it's not working"?
Error message, screenshot, something?
